//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficFines.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverFine
    {
        public int IDDriverFine { get; set; }
        public Nullable<int> IDDriver { get; set; }
        public Nullable<int> IDFine { get; set; }
        public Nullable<int> IDTrafficInspector { get; set; }
        public Nullable<System.DateTime> TimePenalty { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual Fine Fine { get; set; }
        public virtual TrafficInspector TrafficInspector { get; set; }
    }
}
