//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficFines.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrafficPunisment
    {
        public int IDTrafficPunisment { get; set; }
        public Nullable<int> IDTrafficFine { get; set; }
        public Nullable<int> IDTypeOfPunisment { get; set; }
    
        public virtual Fine Fine { get; set; }
        public virtual TypeOfPunishment TypeOfPunishment { get; set; }
    }
}
